deployment:
  kind: DaemonSet

nodeSelector:
  ingress-ready: "true"

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

service:
  type: LoadBalancer

ports:
  web:
    hostPort: 80
  websecure:
    hostPort: 443
