apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
    app.kubernetes.io/name: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
        app.kubernetes.io/name: nextcloud
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 33:33 /var/www/html"]
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html

      containers:
        - name: nextcloud
          image: nextcloud:fpm
          envFrom:
            - configMapRef:
                name: nextcloud-config
            - secretRef:
                name: nextcloud-admin
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-app
                  key: host
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-app
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-app
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-app
                  key: password
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html

        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf

      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data
        - name: nginx-config
          configMap:
            name: nginx-config
