apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress
  namespace: nextcloud
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
spec:
  # ── À AJOUTER : Le bloc TLS qui va déclencher la création du certificat ───
  tls:
    - hosts:
        - nextcloud.local
      secretName: nextcloud-tls
  rules:
    - host: nextcloud.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud
                port:
                  number: 80
